server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
