server:
  port: 0
  # 랜덤 포트 할당
spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 여기에 등록을 하겠다 - eureka service의 주소
      defaultZone: http://127.0.0.1:8761/eureka