server:
  port: 8888
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/project/micro-service-config
        git:
          uri: https://github.com/vitriol95/micro-service-config.git
          # private 이라면 username과 password필요
#          uri: file:///Users/vitri/project/micro-service-config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh